# -*- coding: utf-8 -*-
"""Hatchiyak

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17fZTGBrAXCZPqLUVxtVTC5zh1ofFTQHQ
"""

import pandas as pd

pip install fiona

pip install pyproj

pip install rtree

pip install psycopg2

pip install geoalchemy2

pip install geopy

pip install matplotlib

pip install mapclassify

pip install geopandas

import geopandas as gpd
world_data = gpd.read_file(r'/content/BR_UF_2021.shp')

world_data

world_data = gpd.read_file(r"/content/BR_UF_2021.shp")

world_data.plot()

import geopandas as gpd
  
world_data = gpd.read_file(r'/content/BR_UF_2021.shp')
  
world_data = world_data[['NM_UF', 'geometry']]

world_data['area'] = world_data.area
  
world_data = world_data[world_data['NM_UF'] != 'Minas Gerais']
  
# Changing the projection
current_crs = world_data.crs
world_data.to_crs(epsg=3857, inplace=True)
  
world_data.plot(column='NM_UF', cmap='hsv')

!pip install colormap
import geopandas as gpd
  
# Reading the world shapefile
world_data = gpd.read_file(r'/content/BR_UF_2021.shp')
  
world_data = world_data[['NM_UF', 'geometry']]
  
world_data['area'] = world_data.area
  
# Changing the projection
current_crs = world_data.crs
world_data.to_crs(epsg=3857, inplace=True)
world_data.plot(column='NM_UF', cmap='bone')
  
# Re-calculate the areas in Sq. Km.
world_data['area'] = world_data.area/1000000
  
# Adding a legend
world_data.plot(column='NM_UF', cmap='nipy_spectral_r', legend=True,
                legend_kwds={'label': "Area of the County (Sq. Km.)"}, 
                figsize=(10, 5))

import pandas as pd
from geopandas import GeoDataFrame
from shapely.geometry import Point
import fiona

df = pd.read_csv('data.csv')

geometry = [Point(xy) for xy in zip(df.x, df.y)]
crs = {'init': 'epsg:2263'} #http://www.spatialreference.org/ref/epsg/2263/
geo_df = GeoDataFrame(df, crs=crs, geometry=geometry)

geo_df.to_file(driver='ESRI Shapefile', filename='data.shp')

pip install aquacropeto

pip install swb

pip install aquacrop